In [2]:
import numpy as np
np.__version__

'2.1.3'

In [ ]:
import numpy as np

class ConnectFive:
    def __init__(self):
        self.row_count = 16
        self.column_count = 16
        self.win_length = 5

    def get_initial_state(self):
        return np.zeros((self.row_count, self.column_count))

    def get_next_state(self, state, action, player):
        x, y = action
        state[x, y] = player
        return state
    
    def get_valid_moves(self, state):
        return (state == 0).astype(np.uint8)
    
    def check_win(self, state, action):
        x, y = action
        player = state[x, y]
        
        def count_consecutive(x, y, dx, dy):
            count = 0
            r, c = x, y
            while 0 <= r < self.row_count and 0 <= c < self.column_count and state[r, c] == player:
                count += 1
                r += dx
                c += dy
            return count

        # Check horizontal, vertical, and both diagonal directions
        return (
            count_consecutive(x, y, 0, 1) + count_consecutive(x, y, 0, -1) - 1 >= self.win_length
            or count_consecutive(x, y, 1, 0) + count_consecutive(x, y, -1, 0) - 1 >= self.win_length
            or count_consecutive(x, y, 1, 1) + count_consecutive(x, y, -1, -1) - 1 >= self.win_length
            or count_consecutive(x, y, 1, -1) + count_consecutive(x, y, -1, 1) - 1 >= self.win_length
        )
    
    def get_value_and_terminated(self, state, action):
        if self.check_win(state, action):
            return 1, True
        if np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        return 0, False
    
    def get_opponent(self, player):
        return -player


In [ ]:
connectfive = ConnectFive()
player = 1

state = connectfive.get_initial_state()

while True:
    print(state)
    valid_moves = connectfive.get_valid_moves(state)
    
    # Display valid moves as (x, y) coordinates
    valid_coords = [(i, j) for i in range(connectfive.row_count) for j in range(connectfive.column_count) if valid_moves[i, j] == 1]
    print("Valid moves:", valid_coords)
    
    # Get (x, y) input from the player
    try:
        x, y = map(int, input(f"Player {player}, enter your move as 'x y': ").split())
        action = (x, y)
    except ValueError:
        print("Invalid input format. Please enter two integers separated by a space.")
        continue
    
    # Check if the chosen action is valid
    if valid_moves[action] == 0:
        print("Action not valid. Please choose a valid move.")
        continue
    
    # Update state with the player's move
    state = connectfive.get_next_state(state, action, player)
    
    # Check if the game is over
    value, is_terminal = connectfive.get_value_and_terminated(state, action)
    
    if is_terminal:
        print(state)
        if value == 1:
            print(f"Player {player} won!")
        else:
            print("It's a draw!")
        break
    
    # Switch to the other player
    player = connectfive.get_opponent(player)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Valid moves: [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (3, 0), (3, 1), (3, 2),